export const genresDict = {
  'action': 'боевик',
  'western': 'вестерн',
  'adventure': 'приключения',
  'animation': 'мультфильм',
  'comedy': 'комедия',
  'crime': 'криминал',
  'documentary': 'документальный',
  'drama': 'драма',
  'family': 'семейный',
  'fantasy': 'фэнтези',
  'history': 'история',
  'horror': 'ужасы',
  'music': 'музыка',
  'mystery': 'детектив',
  'romance': 'мелодрама',
  'science fiction': 'фантастика',
  'tv movie': 'телевизионный фильм',
  'thriller': 'триллер',
  'war': 'военный'
}

export const genresIdDict = {
  'action': 28,
  'western': 37,
  'adventure': 12,
  'animation': 16,
  'comedy': 35,
  'crime': 80,
  'documentary': 99,
  'drama': 18,
  'family': 10751,
  'fantasy': 14,
  'history': 36,
  'horror': 27,
  'music': 10402,
  'mystery': 9648,
  'romance': 10749,
  'science fiction': 878,
  'tv movie': 10770,
  'thriller': 53,
  'war': 10752
}